<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    div.panel-heading{
        background: #FAFAFA !important;
        padding: 7px 5px;
    }

    div.panel-heading:hover{
        background: #58ACFA !important;
    }

    .panel-group .panel+.panel{
        margin-top: 0px !important;
    }

    .container{
        padding: 5px 5px !important;
        padding-top: 5px;
    }

    .panel-title{
        font-size: 14px !important;
        color: #444 !important;
    }

    a:hover{
        text-decoration: none !important;
    }
    
    .personalizar-btn-ok{
        position: fixed !important;
        bottom: 0 !important;
    }
</style>
<!-- Latest compiled and minified CSS -->
<!-- Latest compiled and minified JavaScript 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<?php
echo $this->Html->css('game-menu', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('home', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('game-page-title', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('atividades', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('Missao/missao', null, array('media' => 'screen')) . "\n";

echo $this->fetch('css');

echo $this->Html->script('backButtonjs') . "\n";
echo $this->fetch('script');
?>



<?php echo $this->Element('header_menu'); ?>

<div class="jumbotron text-center game-page-title">
   <h4 class="pull-left" id="page-back-btn"><span class="glyphicon glyphicon-menu-left"> </span></h4>  <h4>Personalizar</h4>      
</div> 
<div class="container">


    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Profissões
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="http://prod.static.redskins.clubs.nfl.com/nfl-assets/img/gbl-ico-team/WAS/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Redskins
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://usatftw.files.wordpress.com/2015/09/g9mgk6x3ge26t44cccm9oq1vl.gif?w=660&h=701" alt="...">
                                <div class="carousel-caption">
                                    Raiders
                                </div>
                            </div>
                            <div class="item ">
                                <img src="http://prod.static.vikings.clubs.nfl.com/nfl-assets/img/gbl-ico-team/MIN/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Vikings
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2014/10/philadelphia_eagles_logo_4008.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2015/09/570.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://s-media-cache-ak0.pinimg.com/736x/a1/fb/55/a1fb55b652ef51f2f7f6ea9547dbc3d9.jpg" alt="...">
                                <div class="carousel-caption">
                                    miami dolphins
                                </div>
                            </div>

                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div></div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Guerreiros
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="http://prod.static.redskins.clubs.nfl.com/nfl-assets/img/gbl-ico-team/WAS/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Redskins
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://usatftw.files.wordpress.com/2015/09/g9mgk6x3ge26t44cccm9oq1vl.gif?w=660&h=701" alt="...">
                                <div class="carousel-caption">
                                    Raiders
                                </div>
                            </div>
                            <div class="item ">
                                <img src="http://prod.static.vikings.clubs.nfl.com/nfl-assets/img/gbl-ico-team/MIN/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Vikings
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2014/10/philadelphia_eagles_logo_4008.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2015/09/570.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://s-media-cache-ak0.pinimg.com/736x/a1/fb/55/a1fb55b652ef51f2f7f6ea9547dbc3d9.jpg" alt="...">
                                <div class="carousel-caption">
                                    miami dolphins
                                </div>
                            </div>

                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div></div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
                <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Astrologia
                    </a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="http://prod.static.redskins.clubs.nfl.com/nfl-assets/img/gbl-ico-team/WAS/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Redskins
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://usatftw.files.wordpress.com/2015/09/g9mgk6x3ge26t44cccm9oq1vl.gif?w=660&h=701" alt="...">
                                <div class="carousel-caption">
                                    Raiders
                                </div>
                            </div>
                            <div class="item ">
                                <img src="http://prod.static.vikings.clubs.nfl.com/nfl-assets/img/gbl-ico-team/MIN/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Vikings
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2014/10/philadelphia_eagles_logo_4008.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2015/09/570.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://s-media-cache-ak0.pinimg.com/736x/a1/fb/55/a1fb55b652ef51f2f7f6ea9547dbc3d9.jpg" alt="...">
                                <div class="carousel-caption">
                                    miami dolphins
                                </div>
                            </div>

                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div></div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingFour">
                <h5 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        Militar
                    </a>
                </h5>
            </div>
            <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="collapseFour">
                <div class="panel-body">

                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="http://prod.static.redskins.clubs.nfl.com/nfl-assets/img/gbl-ico-team/WAS/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Redskins
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://usatftw.files.wordpress.com/2015/09/g9mgk6x3ge26t44cccm9oq1vl.gif?w=660&h=701" alt="...">
                                <div class="carousel-caption">
                                    Raiders
                                </div>
                            </div>
                            <div class="item ">
                                <img src="http://prod.static.vikings.clubs.nfl.com/nfl-assets/img/gbl-ico-team/MIN/logos/home/large.png" alt="...">
                                <div class="carousel-caption">
                                    Vikings
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2014/10/philadelphia_eagles_logo_4008.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://usatftw.files.wordpress.com/2015/09/570.png?w=1000" alt="...">
                                <div class="carousel-caption">
                                    ...
                                </div>
                            </div>
                            <div class="item ">
                                <img src="https://s-media-cache-ak0.pinimg.com/736x/a1/fb/55/a1fb55b652ef51f2f7f6ea9547dbc3d9.jpg" alt="...">
                                <div class="carousel-caption">
                                    miami dolphins
                                </div>
                            </div>

                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <button type='button' class='btn btn-primary col-xs-12 col-md-12 personalizar-btn-ok'>OK</button>
</div>

