<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Latest compiled and minified CSS -->
<!-- Latest compiled and minified JavaScript 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<?php
echo $this->Html->css('game-menu', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('home', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('game-page-title', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('atividades', null, array('media' => 'screen')) . "\n";
echo $this->Html->css('Missao/missao', null, array('media' => 'screen')) . "\n";

echo $this->fetch('css');
?>

<style>
    .btn-desafio{
        margin: 2px 0px; 
    }
</style>
<?php echo $this->Element('header_menu'); ?>

<?php
echo $this->Html->script('backButtonjs') . "\n";
echo $this->fetch('script');
?>

<div class="jumbotron text-center game-page-title">
    <h4 class="pull-left" id="page-back-btn"><span class="glyphicon glyphicon-menu-left"> </span></h4> <h4> Desafios</h4>      
</div> 
<div class="container">

    <div class="col-md-12 text-center">
        <div class="col-md-12 btn-group text-center" role="group" aria-label="...">
            <button type="button" value="disponiveis" class="btn btn-default especial-button btn-completo-incompleto active">Disponíveis</button>
            <button type="button" value="finalizadas" class="btn btn-default especial-button btn-completo-incompleto">Finalizadas</button>
        </div>
    </div>
    <br/>
    <!-- Programas Disponíveis -->
    <div class="desafios-disponiveis">
        <ol class="breadcrumb row">
            <li class="col-xs-12"><small>Desafios Disponíveis</small> <span class="label label-default pull-right"></span></li>
        </ol>

        <?php foreach ($desafios as $desafio) { ?>

            <div class="panel panel-default">
                <div class="panel-body painel-missao">
                    <p class=""><span class="glyphicon glyphicon-fire"></span> <small><strong> <?php echo $desafio['desafio']['nome']; ?></strong></small></p>
                    <p><small><small><?php echo $desafio['desafio']['dicatela']; ?></small></small></p>

                    <div class='col-md-5'></div>
                    <div class='col-md-7'>

                        <p>
                            <small><span class='glyphicon glyphicon-user'></span>
                                <?php
                                if (!empty($desafio['jogadordesafios']['isdesafiante'])) {
                                    if ($desafio['jogadordesafios']['isdesafiante'] == 1) {
                                        echo "Você é o <strong>DESAFIANTE</strong>";
                                    } else {
                                        echo "NOME DO GESTOR";
                                    }
                                } else {
                                    echo "NOME DO GESTOR";
                                }
                                ?>
                            </small>
                        </p>
                        <p><small><span class='glyphicon glyphicon-time'></span> <?php
                                $date = date_create($desafio['desafio']['datatermino']);
                                echo 'Válido até ' . date_format($date, "d/m/Y");
                                ?></small></p> 
                        <p><small><span class='glyphicon glyphicon-star-empty'></span> Vale <?php echo '<strong>' . $desafio['desafio']['ganha'] . '</strong>'; ?>  Pontos</small></p>


                        <?php
                        if (!empty($desafio['jogadordesafios']['isdesafiante'])) {
                            if ($desafio['jogadordesafios']['isdesafiante'] == 1) {
                                ?>
                                <a href="../Desafio/escolheDesafiado/<?php echo $desafio['desafio']['id']; ?>">
                                    <button class='btn btn-primary btn-sm col-md-12 col-xs-12' type='button'>ESCOLHA O JOGADOR </button>
                                </a>
                            <?php } else { ?>

                                <button class='btn btn-primary btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>RESPONDER</button><br />
                                <button class='btn btn-danger btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>RESPONDER ANÔNIMO</button><br/>
                                <button class='btn btn-default btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>NÃO RESPONDER</button>
                                <?php
                            }
                        } else {
                            ?>
                            <a href="../Desafio/objetosDesafio/<?php echo $desafio['desafio']['id']; ?>">
                                <button class='btn btn-primary btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>RESPONDER</button>
                            </a><br/>
                            <button class='btn btn-danger btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>RESPONDER ANÔNIMO</button><br/>
                            <button class='btn btn-default btn-sm col-md-12 col-xs-12 btn-desafio' type='button'>NÃO RESPONDER</button>
                        <?php } ?>




                    </div>
                </div> 
            </div>
        <?php } ?>
    </div>

    <!-- Programas Finalizados -->
    <div class="desafios-finalizadas">

    </div>

</div>

